Fix a long time memory leak
turingvideo/rosjava_core pull request #6
Opened 2022-04-01 10:05 UTC by workingenius

2022-04-02 06:51 UTC, lhg-turingvideo approved these changes

2022-04-02 07:37 UTC, hugeturing commented on rosjava/src/main/java/org/ros/internal/node/topic/TopicParticipantManager.java
> +  public void removeSubscriberConnection(DefaultSubscriber<?> subscriber) {
Better name?: removeSubscriberAllConnections

2022-04-02 07:38 UTC, hugeturing commented on rosjava/src/main/java/org/ros/internal/node/topic/TopicParticipantManager.java
> +  public void removePublisherConnection(DefaultPublisher<?> publisher) {
Better name?: removePublisherAllConnections

2022-04-02 07:38 UTC, hugeturing requested changes
Comments added

2022-04-15 03:21 UTC, hugeturing approved these changes

2022-04-18 02:04 UTC, merged